\LoadClass[11pt]{article}

\RequirePackage{fancyhdr}
\RequirePackage{amsmath}
\RequirePackage{amssymb}
\RequirePackage{amsfonts}
\RequirePackage{enumitem}
\RequirePackage{mathtools}
\RequirePackage{algorithm}
\RequirePackage{algpseudocode}
\RequirePackage{interval}
\RequirePackage{graphicx}
\RequirePackage[a4paper, top=2.5cm, bottom=2.5cm, left=2.2cm, right=2.2cm]%
{geometry}

\graphicspath{ {.} }

\newcommand{\Q}{\mathbb{Q}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Z}{\mathbb{Z}}
\DeclareMathOperator{\lcm}{lcm}
\DeclareMathOperator{\tr}{tr}
